### ISSUE TITLE
[feature request] Bridge other chains token to XRPL

### ISSUE THREAD

**Issue by yxxyun** [orbit-chain/bridge-dockerize#26]
Since XRPL also support issue token, it's necessary to bridge other chain's token to XRPL, I think orbit bridge is a ideal solution for this.
official tutorial: https://xrpl.org/issue-a-fungible-token.html
please note that the token issuer send token to the recipient process is similar to the mint transaction on other chain, and the token holder send token back to the issuer process is similar to the burnt transaction on other chain.

**Comment by jaybbbb** [comment]
Thanks for the information.
We will consider it carefully
